export const GET_CATEGORIES_REQUEST = "GET_CATEGORIES_REQUEST";
export const GET_CATEGORIES_SUCCESS = "GET_CATEGORIES_SUCCESS";
export const GET_CATEGORIES_FAIL = "GET_CATEGORIES_FAIL";

export const CREATE_CATEGORIES_REQUEST = "CREATE_CATEGORIES_REQUEST";
export const CREATE_CATEGORIES_SUCCESS = "CREATE_CATEGORIES_SUCCESS";
export const CREATE_CATEGORIES_FAIL = "CREATE_CATEGORIES_FAIL";
export const CREATE_CATEGORIES_RESET = "CREATE_CATEGORIES_RESET";

export const UPDATE_CATEGORIES_REQUEST = "UPDATE_CATEGORIES_REQUEST";
export const UPDATE_CATEGORIES_SUCCESS = "UPDATE_CATEGORIES_SUCCESS";
export const UPDATE_CATEGORIES_FAIL = "UPDATE_CATEGORIES_FAIL";
export const UPDATE_CATEGORIES_RESET = "UPDATE_CATEGORIES_RESET";

export const DELETE_CATEGORIES_REQUEST = "DELETE_CATEGORIES_REQUEST";
export const DELETE_CATEGORIES_SUCCESS = "DELETE_CATEGORIES_SUCCESS";
export const DELETE_CATEGORIES_FAIL = "DELETE_CATEGORIES_FAIL";
export const DELETE_CATEGORIES_RESET = "DELETE_CATEGORIES_RESET";
